Cellfinder migration
brainglobe/brainglobe.github.io pull request #101
Opened 2023-11-15 16:12 UTC by willGraham01

2023-11-20 14:56 UTC, adamltyson requested changes
Looks nice, thanks @willGraham01. I left some comments. 

I'll leave it to you to merge, as I'm not sure what the plan is with cellfinder etc.

2023-11-20 14:56 UTC, adamltyson commented on docs/source/community/developers/repositories/brainglobe-workflows/index.md
Should this be added to the toctree in `docs/source/community/releases/v1/index.md`?

2023-11-20 14:56 UTC, adamltyson commented on docs/source/community/releases/v1/cellfinder-migration.md
> +If you really want to keep using the old `cellfinder` (CLI) tool, you will need to prevent further updates to cellfinder (package).
I find this section a bit confusing. `brainglobe-workflows` is presented as the new, supported way of using what is currently called the cellfinder CLI. This section however says "If you really want to". As a user, I'd be thinking, "I do, because you just told me that's what I should do!".

2023-11-20 14:56 UTC, adamltyson commented on docs/source/documentation/brainglobe-workflows/index.md
Should this link to the cellfinder CLI docs somewhere?

2023-11-20 14:56 UTC, adamltyson commented on docs/source/community/developers/repositories/brainglobe-workflows/index.md
> +# `brainglobe-workflows`
This is (I think) the only heading in the docs that's formatted as code
```suggestion
# brainglobe-workflows
```

2023-11-20 14:56 UTC, adamltyson commented on docs/source/community/developers/index.md
This might be better as a seperate issue, but the toctrees in this page make for a confusing left hand navigation bar. It's entirely content in other pages, and not the content of this page itself. In particular, I don't think the left hand navigation bar should contain links to the individual repo pages.

2023-11-20 15:18 UTC, adamltyson commented
> I'll leave it to you to merge, as I'm not sure what the plan is with cellfinder etc.

Sorry, I just saw your zulip message.

2023-11-22 09:24 UTC, willGraham01 commented on docs/source/community/developers/index.md
Getting rid of the toctree at the bottom of the page seems to remove these links from the rendered website

2023-11-23 12:37 UTC, adamltyson approved these changes
I've left a few suggestions. The only thing that needs to be changed is to somehow link to the repo-specific dev docs.

2023-11-23 12:37 UTC, adamltyson commented on docs/source/community/developers/index.md
They still need to be linked somewhere right? I don't think users can access them currently.

2023-11-23 12:37 UTC, adamltyson commented on docs/source/community/releases/v1/cellfinder-migration.md
> +## `brainglobe-workflows`
For consistency 
```suggestion
## brainglobe-workflows
```

2023-11-23 12:37 UTC, adamltyson commented on docs/source/community/releases/v1/cellfinder-migration.md
> +### Delaying my Update
```suggestion
### Delaying updating
```

2023-11-23 13:34 UTC, willGraham01 commented
> The only thing that needs to be changed is to somehow link to the repo-specific dev docs

If we include them in a toctree they pollute the side-nav bar as we saw.

We could just hard-link to them from the developers main page? Or just have a lookup page that has each individual repo in it's index?

2023-11-23 13:51 UTC, adamltyson commented
> If we include them in a toctree they pollute the side-nav bar as we saw.

is it worth just creating a new "Specific repo developer docs" page that can be linked here, and that page will contain links to individual repos?

2023-11-23 13:59 UTC, willGraham01 commented
>  Or just have a lookup page that has each individual repo in it's index?
> is it worth just creating a new "Specific repo developer docs" page that can be linked here, and that page will contain links to individual repos?

Yeah that's probably the best approach if we don't want to pollute the sidebar, but also want to make sure that sphinx takes care of the build for us. Will whip up a stub page in next push

2023-11-24 11:44 UTC, adamltyson approved these changes
Excellent, thanks @willGraham01

2023-11-24 11:44 UTC, merged