a little bit more doc for si-probe tracking with 1D segmentation
brainglobe/brainglobe.github.io pull request #134
Opened 2024-01-05 00:27 UTC by jingjie-li

2024-01-05 12:05 UTC, adamltyson requested changes
Thanks for this @jingjie-li, much appreciated! I've left a few comments, and some suggestions just to standardise formatting with the rest of the website.

2024-01-05 21:58 UTC, jingjie-li commented on docs/source/tutorials/silicon-probe-tracking.md
> +For example: (package importing and rendering code can refer to [this example](https://github.com/brainglobe/brainrender/blob/main/examples/add_cells.py))
Yes it's better to have a full example here. but it's a bit strange to put that much code in the doc. And it need the `.npy` file to run. Can I put those as an example in `brainrender` repo and also attached the example data file and then attach that link here?

2024-01-05 23:11 UTC, jingjie-li commented on docs/source/documentation/brainglobe-segmentation/user-guide/output-files.md
yes I have moved it to tutorial.

2024-01-05 23:12 UTC, jingjie-li commented on docs/source/documentation/brainglobe-segmentation/user-guide/output-files.md
> ++ `xxx.csv` a csv table that summrize the depth, brain area, brain region ID (based on allen atlas) for each point of the fitted spline. [example](https://github.com/brainglobe/brainglobe-segmentatio
got it

2024-01-08 10:30 UTC, adamltyson commented on docs/source/tutorials/silicon-probe-tracking.md
> +For example: (package importing and rendering code can refer to [this example](https://github.com/brainglobe/brainrender/blob/main/examples/add_cells.py))
I'm not sure it's so strange. I think it's something that lots of people will want to do. You could either add it to the brainrender examples along with the `.npy` file (feel free to raise a PR), or just add it here without the data making it obvious where to add the path to the file (e.g. `.path/to/brainrender_export.npy`).

2024-01-10 17:42 UTC, jingjie-li commented on docs/source/tutorials/silicon-probe-tracking.md
> +For example: (package importing and rendering code can refer to [this example](https://github.com/brainglobe/brainrender/blob/main/examples/add_cells.py))
I have linked this example to `brainrender` repo, here is the PR: https://github.com/brainglobe/brainrender/pull/313

2024-01-11 17:12 UTC, adamltyson approved these changes
Great, thanks @jingjie-li. I made some small changes but I think this is good to go :tada:

2024-01-11 17:15 UTC, merged