Add a note about collaboration on atlas standards
brainglobe/brainglobe.github.io pull request #262
Opened 2024-11-08 12:32 UTC by adamltyson

@PolarBean feel free to suggest any changes. Happy to add any logos to the funders page too.

2024-11-08 13:03 UTC, PolarBean commented
and link to https://www.ebrains.eu/national-nodes/norway

2024-11-08 13:21 UTC, adamltyson commented on docs/source/about.md
> +We collaborate with the [EBRAINS](https://www.ebrains.eu/) national node at the [University of Oslo](https://www.uio.no/english/) to establish and implement standards for atlases and their metadata.
```suggestion
We collaborate with researchers from the [EBRAINS national node](https://www.ebrains.eu/national-nodes/norway) at the [University of Oslo](https://www.uio.no/english/) to establish and implement standards for atlases and their metadata.
```

2024-11-08 13:22 UTC, adamltyson commented
How's this version?

2024-11-12 13:32 UTC, PolarBean commented
Good! I ran it by Jan and he asked if we could have it as the following 
"We collaborate with the [EBRAINS Norwegian node](https://www.ebrains.eu/national-nodes/norway) based at [the University of Oslo](https://www.uio.no/english/), to establish and implement standards and tools for atlases and their metadata."

Also it would be cool to have the UiO logo on the funders page, Jan has to double check before adding the EBRAINS logo. Let me know if this all sounds OK or if it's too much.

2024-11-12 13:35 UTC, PolarBean requested changes
We collaborate with researchers from the [EBRAINS Norwegian node](https://www.ebrains.eu/national-nodes/norway) based at [the University of Oslo](https://www.uio.no/english/), to establish and implement standards and tools for atlases and their metadata

2024-11-12 13:39 UTC, PolarBean commented
both dark and light mode logos are here: https://www.uio.no/english/about/designmanual/profile-elements/logo/

2024-11-12 14:28 UTC, adamltyson commented
@PolarBean I think this should be good. Happy to add the EBRAINS logo at a later date.

2024-11-12 21:18 UTC, PolarBean commented
Great! I'm happy for it to be merged

2024-11-13 08:14 UTC, merged